__include__: [
  '../dataset/widerface_keypoints_working.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  '../rtdetrv2/include/rtdetrv2_r50vd.yml',
]

output_dir: ./output/rtdetr_r50vd_widerface_keypoints_rotation_debug

num_classes: 1

epoches: 1

RTDETRTransformerv2:
  num_queries: 100
  use_keypoints: true
  num_keypoints: 5
  keypoint_heatmap_size: 64

train_dataloader:
  dataset:
    type: WiderFaceKeypointDatasetWorking
    transforms:
      type: Compose
      ops:
        - {type: RandomRotationWithKeypoints, degrees: 15, fill: 0, p: 1.0}
        - {type: Resize, size: [640, 640]}
        - {type: NormalizeKeypoints}
        - {type: ConvertPILImage, dtype: 'float32', scale: True}
        - {type: ConvertBoxes, fmt: 'cxcywh', normalize: True}
      policy:
        name: default
  collate_fn:
    type: BatchImageCollateFuncion
    scales: ~

batch_size: 4

RTDETRPostProcessor:
  use_keypoints: true
  remap_widerface_category: true
  num_top_queries: 100

RTDETRCriterionv2:
  use_keypoints: true
  keypoint_loss_weight: 1.0
  weight_dict:
    loss_vfl: 1
    loss_bbox: 5
    loss_giou: 2
    loss_keypoint: 6.0
    loss_keypoint_heatmap: 5.0
    loss_keypoint_offset: 0.2

optimizer:
  type: AdamW
  params:
    - {params: '^(?=.*(?:norm|bn)).*$', weight_decay: 0.}
    - {params: '^(?=.*keypoint).*$', lr: 5.e-5, weight_decay: 1.e-4}
  lr: 2.e-5
  weight_decay: 1.e-4
