__include__: [
  '../dataset/widerface_keypoints_working.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  '../rtdetrv2/include/rtdetrv2_r50vd.yml',
]

output_dir: ./output/rtdetr_r50vd_widerface_keypoints_working

# Override for single class (faces)
num_classes: 1

# PHASE 1: MINIMAL WORKING BASELINE
# Start with absolute minimal transforms to verify GT alignment
epoches: 5  # Quick test
eval_freq: 5
checkpoint_freq: 1

# Face detection + keypoint localization settings
RTDETRTransformerv2:
  num_queries: 100
  use_keypoints: true
  num_keypoints: 5
  keypoint_heatmap_size: 64

# PHASE 2: Adding TorchVision transforms step by step
train_dataloader: 
  dataset: 
    type: WiderFaceKeypointDatasetWorking  # Use working dataset
    transforms:
      type: Compose
      ops:
        - {type: RandomPhotometricDistort, p: 0.5}  # Step 1: Color only (safe)  
        - {type: RandomHorizontalFlip, p: 0.5}     # Step 2: Test keypoint L/R swap
        - {type: WorkingRotation, degrees: 15, p: 0.5}  # Step 3: Rotation augmentation
        - {type: RandomZoomOut, fill: 0}              # Step 4: Zoom augmentation
        - {type: RandomIoUCrop, p: 0.8}              # Step 5: Crop augmentation
        - {type: Resize, size: [640, 640]}
        - {type: ConvertPILImage, dtype: 'float32', scale: True}
        - {type: ConvertBoxes, fmt: 'cxcywh', normalize: True}
  collate_fn:
    type: BatchImageCollateFuncion
    scales: ~  # No multi-scale for now

batch_size: 4

# Enable keypoint processing in PostProcessor
RTDETRPostProcessor:
  use_keypoints: true
  remap_widerface_category: true
  num_top_queries: 100

# Keypoint loss with moderate weights
RTDETRCriterionv2:
  use_keypoints: true
  keypoint_loss_weight: 1.0
  weight_dict: 
    loss_vfl: 1
    loss_bbox: 5 
    loss_giou: 2
    loss_keypoint: 2.0
    loss_keypoint_heatmap: 1.0
    loss_keypoint_offset: 0.5

optimizer:
  type: AdamW
  params:
    - 
      params: '^(?=.*(?:norm|bn)).*$'
      weight_decay: 0.
    -
      params: '^(?=.*keypoint).*$'
      lr: 1.e-3
      weight_decay: 1.e-4
  lr: 2.e-5
  weight_decay: 1.e-4